### ISSUE TITLE
comment

### ISSUE THREAD

**Issue by dltmdrbtjd** [jsw4215/react_project#1]
- 프로젝트 마무리 수고 많으셨습니다 😎 

- 전체적으로 이번 프로젝트 마무리는 잘 하신것 같습니다 ! 조금 더 보완했다면 좋은점들은 우선 컴포넌트의 분리가 따로 되어있지 않다는게 아쉬운 부분중 하나인것 같습니다. singleBox는 폴더는 아마 상세페이지 관련 컴포넌트들을 모아놓으신걸로 보입니다. 이건 좋은 분리 입니다 ! 하지만 그 외에 AddWord, WordBoxList등등도 같이 components라는 폴더의 이름으로 컴포넌트들을 별도로 분리해서 작업하시면 나중에 구조를 보기도 쉽고 협업에 있어서도 중요한 부분입니다. 추가적으로 분리해보면 좋은건 css들은 styles폴더로 분리하고 firebase와 같은 third party들은 service 또는 firebase라는 폴더로 분리시켜서 구조를 조금 변경해보신다면 실제로도 좀 더 구조가 한 눈에 들어오실거에요 ! 😄

**Comment by jsw4215** [comment]
오 리뷰 감사합니다 ㅎㅎ
말씀드린대로 설계 구조 신경써서 다음 프로젝트 진행해 보겠습니다
감사합니다 ㅎㅎ
